###
POST http://localhost:8080/actors
Content-Type: application/json

{
  "type": "PARTNER_STORE_OWNER",
  "name": "John Doe"
}

###
POST http://localhost:8080/actors
Content-Type: application/json

{
  "type": "PICKUP_DRIVER",
  "name": "Mary Jane2"
}

###
POST http://localhost:8080/actors
Content-Type: application/json

{
  "type": "SYSTEM_AUTO",
  "name": "SYSTEM_AUTO"
}

### actor 전체 조회
GET http://localhost:8080/actors

###
POST http://localhost:8080/stores
Content-Type: application/json

{
  "name": "Store 1",
  "address": "123 Main"
}

### store 전체 조회
GET http://localhost:8080/stores

###
POST {{host}}/pickups
Content-Type: application/json

{
  "actorId": "01J35TVJKT2NT3WJFSTQ3C7AX6",
  "storeId": "01J35TXCVCZ27VZHWZQ7VSD452",
  "desc": "Please pick up the items."
}

###
PATCH {{host}}/pickups/01J368N1XFJSF8D2C9439GTPHM/accept
Content-Type: application/json

{
  "actorId": "01J35TW0D7V812DS2Y8QRCXJA9"
}

###
PATCH {{host}}/pickups/01J368E2AT3BGSHJC4QA0C8J5X/process
Content-Type: application/json

{
  "actorId": "01J35TW0D7V812DS2Y8QRCXJA9"
}

###
PATCH {{host}}/pickups/01J368E2AT3BGSHJC4QA0C8J5X/approve
Content-Type: application/json

{
  "actorId": "01J35TVJKT2NT3WJFSTQ3C7AX6"
}

### pickup 조회
GET {{host}}/pickups?pickupId=01J368E2AT3BGSHJC4QA0C8J5X

### pickup 조건 조회
GET http://localhost:8080/pickups?
    storeId=01J35TXCVCZ27VZHWZQ7VSD452
    &startedAt=2024-07-19T19:45:19.218114Z
    &endedAt=2024-07-19T19:50:20.218114Z
